
/*Foreground defined colors  */
#define Black_FG "\x1B[30m" 
#define Red_FG "\x1B[31m"
#define Green_FG "\x1B[32m"
#define Yellow_FG "\x1B[33m"
#define Blue_FG "\x1B[34m"
#define Magenta_FG "\x1B[35m" 
#define Cyan_FG "\x1B[36m"
#define White_FG "\x1B[37m" 
#define Bright_Black_FG "\x1B[90m"
#define Bright_Red_FG "\x1B91m"
#define Bright_Green_FG "\x1B92m" 
#define Bright_Yellow_FG "\x1B93m" 
#define Bright_Blue_FG "\x1B94m"
#define Bright_Magenta_FG "\x1B95m" 
#define Bright_Cyan_FG "\x1B96m"
#define Bright_White_FG "\x1B97m"
/*Background defined color*/
#define Black_BG  "\x1B40m"
#define Red_BG "\x1B41m"
#define Green_BG "\x1B42m"
#define Yellow_BG "\x1B43m" 
#define Blue_BG "\x1B44m"
#define Magenta_BG "\x1B45m" 
#define Cyan_BG "\x1B46m"
#define White_BG "\x1B47m" 
#define Bright_Black_BG "\x1B100m"
#define Bright_Red_BG "\x1B101m"
#define Bright_Green_BG "\x1B102m" 
#define Bright_Yellow_BG "\x1B103m" 
#define Bright_Blue_BG "\x1B104m"
#define Bright_Magenta_BG "\x1B105m" 
#define Bright_Cyan_BG "\x1B106m"
#define Bright_White_BG "\x1B107m"
/*Reset color : default terminal output color*/
#define Reset_Color "\033[0m\t\t"
